/*
 * This file is generated by jOOQ.
 */
package com.kotlinspring.infrastructure.db.tables.daos


import com.kotlinspring.infrastructure.db.tables.Teacher
import com.kotlinspring.infrastructure.db.tables.records.TeacherRecord

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl
import org.springframework.stereotype.Repository


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
@Repository
open class TeacherDao(configuration: Configuration?) : DAOImpl<TeacherRecord, com.kotlinspring.infrastructure.db.tables.pojos.Teacher, Int>(Teacher.TEACHER, com.kotlinspring.infrastructure.db.tables.pojos.Teacher::class.java, configuration) {

    /**
     * Create a new TeacherDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: com.kotlinspring.infrastructure.db.tables.pojos.Teacher): Int? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Int?, upperInclusive: Int?): List<com.kotlinspring.infrastructure.db.tables.pojos.Teacher> = fetchRange(Teacher.TEACHER.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Int): List<com.kotlinspring.infrastructure.db.tables.pojos.Teacher> = fetch(Teacher.TEACHER.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Int): com.kotlinspring.infrastructure.db.tables.pojos.Teacher? = fetchOne(Teacher.TEACHER.ID, value)

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfName(lowerInclusive: String, upperInclusive: String): List<com.kotlinspring.infrastructure.db.tables.pojos.Teacher> = fetchRange(Teacher.TEACHER.NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    fun fetchByName(vararg values: String): List<com.kotlinspring.infrastructure.db.tables.pojos.Teacher> = fetch(Teacher.TEACHER.NAME, *values)
}
