/*
 * This file is generated by jOOQ.
 */
package com.kotlinspring.infrastructure.db.enums


import com.kotlinspring.infrastructure.db.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class Courseapprovalstatus(@get:JvmName("literal") public val literal: String) : EnumType {
    PENDING("PENDING"),
    APPROVED("APPROVED");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "CourseApprovalStatus"
    override fun getLiteral(): String = literal
}
