/*
 * This file is generated by jOOQ.
 */
package com.kotlinspring.infrastructure.db.tables


import com.kotlinspring.infrastructure.db.Public
import com.kotlinspring.infrastructure.db.enums.Courseapprovalstatus
import com.kotlinspring.infrastructure.db.keys.COURSE_PKEY
import com.kotlinspring.infrastructure.db.keys.COURSE__COURSE_TEACHERID_FKEY
import com.kotlinspring.infrastructure.db.tables.Teacher.TeacherPath
import com.kotlinspring.infrastructure.db.tables.records.CourseRecord

import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Course(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CourseRecord>?,
    parentPath: InverseForeignKey<out Record, CourseRecord>?,
    aliased: Table<CourseRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CourseRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.Course</code>
         */
        val COURSE: Course = Course()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CourseRecord> = CourseRecord::class.java

    /**
     * The column <code>public.Course.id</code>.
     */
    val ID: TableField<CourseRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.Course.name</code>.
     */
    val NAME: TableField<CourseRecord, String?> = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.Course.category</code>.
     */
    val CATEGORY: TableField<CourseRecord, String?> = createField(DSL.name("category"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.Course.teacherId</code>.
     */
    val TEACHERID: TableField<CourseRecord, Int?> = createField(DSL.name("teacherId"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.Course.approvalStatus</code>.
     */
    val APPROVALSTATUS: TableField<CourseRecord, Courseapprovalstatus?> = createField(DSL.name("approvalStatus"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'PENDING'::\"CourseApprovalStatus\""), SQLDataType.VARCHAR)).asEnumDataType(Courseapprovalstatus::class.java), this, "")

    private constructor(alias: Name, aliased: Table<CourseRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CourseRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CourseRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.Course</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.Course</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.Course</code> table reference
     */
    constructor(): this(DSL.name("Course"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CourseRecord>?, parentPath: InverseForeignKey<out Record, CourseRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, COURSE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CoursePath : Course, Path<CourseRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CourseRecord>?, parentPath: InverseForeignKey<out Record, CourseRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CourseRecord>): super(alias, aliased)
        override fun `as`(alias: String): CoursePath = CoursePath(DSL.name(alias), this)
        override fun `as`(alias: Name): CoursePath = CoursePath(alias, this)
        override fun `as`(alias: Table<*>): CoursePath = CoursePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<CourseRecord> = COURSE_PKEY
    override fun getReferences(): List<ForeignKey<CourseRecord, *>> = listOf(COURSE__COURSE_TEACHERID_FKEY)

    private lateinit var _teacher: TeacherPath

    /**
     * Get the implicit join path to the <code>public.Teacher</code> table.
     */
    fun teacher(): TeacherPath {
        if (!this::_teacher.isInitialized)
            _teacher = TeacherPath(this, COURSE__COURSE_TEACHERID_FKEY, null)

        return _teacher;
    }

    val teacher: TeacherPath
        get(): TeacherPath = teacher()
    override fun `as`(alias: String): Course = Course(DSL.name(alias), this)
    override fun `as`(alias: Name): Course = Course(alias, this)
    override fun `as`(alias: Table<*>): Course = Course(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Course = Course(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Course = Course(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Course = Course(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Course = Course(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Course = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Course = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Course = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Course = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Course = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Course = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Course = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Course = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Course = where(DSL.notExists(select))
}
