/*
 * This file is generated by jOOQ.
 */
package com.kotlinspring.infrastructure.db.sequences


import com.kotlinspring.infrastructure.db.Public

import org.jooq.Sequence
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType



/**
 * The sequence <code>public.teacher_id_seq</code>
 */
val TEACHER_ID_SEQ: Sequence<Long> = Internal.createSequence("teacher_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null)
