/*
 * This file is generated by jOOQ.
 */
package com.kotlinspring.infrastructure.db.tables.pojos


import com.kotlinspring.infrastructure.db.enums.Courseapprovalstatus

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Table

import java.io.Serializable
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
@Entity
@Table(
    name = "Course",
    schema = "public"
)
data class Course(
    @get:Id
    @get:Column(name = "id")
    var id: UUID? = null,
    @get:Column(name = "name", nullable = false)
    var name: String,
    @get:Column(name = "category", nullable = false)
    var category: String,
    @get:Column(name = "teacherId")
    var teacherid: Int? = null,
    @get:Column(name = "approvalStatus")
    var approvalstatus: Courseapprovalstatus? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Course = other as Course
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.name != o.name)
            return false
        if (this.category != o.category)
            return false
        if (this.teacherid == null) {
            if (o.teacherid != null)
                return false
        }
        else if (this.teacherid != o.teacherid)
            return false
        if (this.approvalstatus == null) {
            if (o.approvalstatus != null)
                return false
        }
        else if (this.approvalstatus != o.approvalstatus)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.name.hashCode()
        result = prime * result + this.category.hashCode()
        result = prime * result + (if (this.teacherid == null) 0 else this.teacherid.hashCode())
        result = prime * result + (if (this.approvalstatus == null) 0 else this.approvalstatus.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Course (")

        sb.append(id)
        sb.append(", ").append(name)
        sb.append(", ").append(category)
        sb.append(", ").append(teacherid)
        sb.append(", ").append(approvalstatus)

        sb.append(")")
        return sb.toString()
    }
}
