/*
 * This file is generated by jOOQ.
 */
package com.kotlinspring.infrastructure.db.tables.references


import com.kotlinspring.infrastructure.db.tables.Course
import com.kotlinspring.infrastructure.db.tables.Teacher
import com.kotlinspring.infrastructure.db.tables.User
import com.kotlinspring.infrastructure.db.tables._PrismaMigrations



/**
 * The table <code>public._prisma_migrations</code>.
 */
val _PRISMA_MIGRATIONS: _PrismaMigrations = _PrismaMigrations._PRISMA_MIGRATIONS

/**
 * The table <code>public.Course</code>.
 */
val COURSE: Course = Course.COURSE

/**
 * The table <code>public.Teacher</code>.
 */
val TEACHER: Teacher = Teacher.TEACHER

/**
 * The table <code>public.User</code>.
 */
val USER: User = User.USER
